runtime: python310

entrypoint: waitress-serve --port $PORT --call 'alpharius.web:create_app'

handlers:
  - url: /static
    static_files: alpharius/web/static
    upload: alpharius/web/static/(.+)
  - url: /.*
    script: auto

env_variables:
  APCA_API_KEY_ID: ""
  APCA_API_SECRET_KEY: ""
  APCA_API_BASE_URL: ""
  CASH_RESERVE: ""
  SECRET_KEY: ""

instance_class: F1
