version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pytest-cov
          command: pip install pytest-cov
      - run:
          name: Run tests
          command: pytest --cov-config=.coveragerc --cov=alpharius
      - run:
          name: Upload to codecov
          command:
            - curl -Os https://uploader.codecov.io/latest/linux/codecov
            - chmod +x codecov
            - ./codecov

workflows:
  main:
    jobs:
      - build-and-test