version: 2.1

orbs:
  python: codecov/codecov@3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install codecov
          command: pip install codecov
      - run:
          name: Install pytest-cov
          command: pip install pytest-cov
      - run:
          name: Run tests
          command: pytest --cov-config=.coveragerc --cov=alpharius
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-and-test