name: Unit Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install package
        run: make
      - name: Install pytest-cov
        run: pip3 install pytest-cov
      - name: Run test
        run: pytest --cov-config=.coveragerc --cov=alpharius
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
